# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherViper' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  	# Pods for WeatherViper
	
	# VIPER
	pod 'LightRoute', :git => 'https://github.com/SpectralDragon/LightRoute.git'
  	pod 'Swinject'
  	pod 'SwinjectStoryboard'
	
	# Save Data
	pod 'RealmSwift'

	# Networking
	pod 'Alamofire'

	# Custom UI

  target 'WeatherViperTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
